version: "3.8"

services:
  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "5000:5000"
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
